version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - cloudnet
  mysqldb:
    image: mysqldb
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: cloudproject
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - cloudnet
    volumes:
      - .m2:/root/.m2
  users:
    image: user-service:latest
    restart: always
    ports:
      - "8083:8083"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cloudproject?allowPublicKeyRetrieval=true   
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb 
      - redis      
networks:
  cloudnet: