version: '3'

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    networks:
      - cloudnet
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - cloudnet
  mysqldb:
    image: mysqldb
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: cloudproject
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - cloudnet
    volumes:
      - .m2:/root/.m2
  users:
    image: user-service:latest
    container_name: users
    restart: always
    ports:
      - "8083:8083"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cloudproject?allowPublicKeyRetrieval=true   
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb 
      - redis   
      

  pet:
    image: pet-service:latest
    container_name: pet
    restart: always
    ports:
      - "8081:8081"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cloudproject?allowPublicKeyRetrieval=true   
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb 
      - redis 
      - users
      - health   

  health:
    image: health-service:latest
    container_name: health
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cloudproject?allowPublicKeyRetrieval=true   
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb 
      - redis   

  adoption:
    image: adoption-service:latest
    container_name: adoption
    restart: always
    ports:
      - "8082:8082"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cloudproject?allowPublicKeyRetrieval=true   
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb 
      - redis     
networks:
  cloudnet: