version: '3'

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    networks:
      - cloudnet
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - cloudnet

  mysqldb_user:
    image: mysqldb_user
    container_name: mysqldb_user
    restart: always
    environment:
      MYSQL_DATABASE: cloudproject
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - cloudnet
    volumes:
      - .m2_user:/root/.m2

  mysqldb_pet:
    image: mysqldb_pet
    container_name: mysqldb_pet
    restart: always
    environment:
      MYSQL_DATABASE: petproject
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - cloudnet
    volumes:
      - .m2_pet:/root/.m2

  mysqldb_adoption:
    image: mysqldb_adoption
    container_name: mysqldb_adoption
    restart: always
    environment:
      MYSQL_DATABASE: adoptionproject
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - cloudnet
    volumes:
      - .m2_adoption:/root/.m2

  mysqldb_health:
    image: mysqldb_health
    container_name: mysqldb_health
    restart: always
    environment:
      MYSQL_DATABASE: healthproject
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - cloudnet
    volumes:
      - .m2_health:/root/.m2

  users:
    image: user-service:latest
    container_name: users
    restart: always
    ports:
      - "8083:8083"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb_user:3306/cloudproject?allowPublicKeyRetrieval=true
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb_user
      - redis   
      

  pet:
    image: pet-service:latest
    container_name: pet
    restart: always
    ports:
      - "8081:8081"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb_pet:3306/petproject?allowPublicKeyRetrieval=true
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb_pet
      - redis 
      - users
      - health   

  health:
    image: health-service:latest
    container_name: health
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb_health:3306/healthproject?allowPublicKeyRetrieval=true
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb_health
      - redis   

  adoption:
    image: adoption-service:latest
    container_name: adoption
    restart: always
    ports:
      - "8082:8082"
    networks:
      - cloudnet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb_adoption:3306/adoptionproject?allowPublicKeyRetrieval=true
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb_adoption
      - redis     
networks:
  cloudnet: